version: 2

sources:
  - name: dbt_handson_raw
    database: postgres
    schema: dbt_handson_raw  
    tables:
      - name: countries
      - name: population

models:
  - name: population_enriched
    columns:
      - name: country_id
        tests:
          - not_null
      - name: country_code
        tests:
          - not_null
      - name: region
        tests:
          - not_null
      - name: population
        tests:
          - not_null